apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: default
      group_by: ["alertname", "severity"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
    receivers:
      - name: default
        webhook_configs:
          - url: http://placeholder-webhook.default.svc.cluster.local/
            send_resolved: true
