apiVersion: apps/v1
kind: Deployment
metadata:
  name: sar-backend
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sar-frontend
spec:
  replicas: 2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sar-backend
spec:
  minReplicas: 3
  maxReplicas: 10
