apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - pvc-chroma.yaml
  - pvc-ollama.yaml
  - postgres-statefulset.yaml
  - ollama-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: sar-backend
    newName: ghcr.io/sujalsune92/sar-backend
    newTag: latest
  - name: sar-frontend
    newName: ghcr.io/sujalsune92/sar-frontend
    newTag: latest
