apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sar-ingress
spec:
  rules:
    - host: sar-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sar-frontend
                port:
                  number: 80
